apiVersion: usernaut.dev/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: platformadmin-group
spec:
  group_name: dataverse-aggregate-bookingsmaster
  members:
  - shikgupt
  backends:
  - name: fivetran
    type: fivetran
  